import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Nunito, PT_Sans } from 'next/font/google'
import Provider from './provider'

import './globals.css'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin']
})

const ptSans = PT_Sans({
  variable: '--font-pt-sans',
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${nunito.variable} ${ptSans.variable} antialiased relative`}>
          <div className="texture" />
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}
